{
 "title": "Agent Telemetry",
 "time": { "from": "now-7d", "to": "now" },
 "refresh": "5s",
 "templating": {
  "list": [
   {
    "name": "Hostname",
    "label": "hostname",
    "query": "SELECT \"/srl_nokia_system:system/srl_nokia_system_name:name_host-name\" FROM \"SRL_all\""
   }
  ]
 },
 "panels": [
  {
   "title": "Prefix monitoring",
   "type": "table",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "targets": [
    {
     "measurement": "SRL_docter-agent",
     "query": "SELECT source AS \"Node\",  \"/docter_agent:docter_agent/health/route_status\" AS \"Status\" FROM \"SRL_docter-agent\" WHERE $timeFilter",
     "select": [
      [
       {
        "params": [
         "/docter_agent:docter_agent/health/route_status"
        ],
        "type": "field"
       },
       { "params": [ "Status" ], "type": "alias" }
      ]
     ]
    }
   ]
  },
  {
   "title": "Prefix Availability",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "groupBy": [
      { "params": [ "source" ], "type": "tag" }
     ],
     "measurement": "SRL_docter-agent",
     "query": "SELECT source AS \"Node\",  \"/docter_agent:docter_agent/health/route_availability\" AS \"Availability\" FROM \"SRL_docter-agent\" WHERE $timeFilter",
     "select": [
      [
       {
        "params": [
         "/docter_agent:docter_agent/health/route_status"
        ],
        "type": "field"
       },
       { "params": [ "Status" ], "type": "alias" }
      ]
     ]
    }
   ]
  },
  {
   "title": "Topology",
   "type": "agenty-flowcharting-panel",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 8 },
   "format": "short",
   "valueName": "current",
   "targets": [
    {
     "alias": "route_status_leaf1",
     "measurement": "SRL_docter-agent",
     "select": [
      [
       {
        "params": [
         "/docter_agent:docter_agent/health/route_status"
        ],
        "type": "field"
       }
      ]
     ],
     "tags": [
      { "key": "source", "operator": "=", "value": "clab-srl-docter-lab-leaf1" }
     ]
    },
    {
     "alias": "route_status_leaf2",
     "measurement": "SRL_docter-agent",
     "select": [
      [
       {
        "params": [
         "/docter_agent:docter_agent/health/route_status"
        ],
        "type": "field"
       }
      ]
     ],
     "tags": [
      { "key": "source", "operator": "=", "value": "clab-srl-docter-lab-leaf2" }
     ]
    },
    {
     "alias": "route_status_leaf3",
     "measurement": "SRL_docter-agent",
     "select": [
      [
       {
        "params": [
         "/docter_agent:docter_agent/health/route_status"
        ],
        "type": "field"
       }
      ]
     ],
     "tags": [
      { "key": "source", "operator": "=", "value": "clab-srl-docter-lab-leaf3" }
     ]
    },
    {
     "alias": "route_status_spine1",
     "measurement": "SRL_docter-agent",
     "select": [
      [
       {
        "params": [
         "/docter_agent:docter_agent/health/route_status"
        ],
        "type": "field"
       }
      ]
     ],
     "tags": [
      { "key": "source", "operator": "=", "value": "clab-srl-docter-lab-spine1" }
     ]
    },
    {
     "alias": "route_status_spine2",
     "measurement": "SRL_docter-agent",
     "select": [
      [
       {
        "params": [
         "/docter_agent:docter_agent/health/route_status"
        ],
        "type": "field"
       }
      ]
     ],
     "tags": [
      { "key": "source", "operator": "=", "value": "clab-srl-docter-lab-spine2" }
     ]
    }
   ]
  },
  {
   "title": "Events",
   "type": "table",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 16 },
   "targets": [
    {
     "alias": "session state",
     "measurement": "SRL_docter-agent",
     "query": "SELECT source AS \"Node\", \"/docter_agent:docter_agent/health/route_availability\" AS \"route_availability\", \"/docter_agent:docter_agent/health/route_status\" AS \"route_status\", \"/docter_agent:docter_agent/reports/events_name\" AS \"events_name\", \"/docter_agent:docter_agent/reports/events_sample-period\" AS \"events_sample-period\", \"/docter_agent:docter_agent/reports/events_timestamp\" AS \"events_timestamp\", \"/docter_agent:docter_agent/reports/events_trigger\" AS \"events_trigger\", \"/docter_agent:docter_agent/reports/events_values_0\" AS \"events_values_0\", \"/docter_agent:docter_agent/reports/events_values_1\" AS \"events_values_1\", \"/docter_agent:docter_agent/reports/events_values_2\" AS \"events_values2\", \"/docter_agent:docter_agent/reports/history/path/event_v\" AS \"event_v\", \"/docter_agent:docter_agent/reports_count\" AS \"reports_count\", \"/docter_agent:docter_agent/reports_filtered\" AS \"reports_filtered\", \"/docter_agent:docter_agent/reports_last-updated\" AS \"reports_last-updated\" FROM \"SRL_docter-agent\" WHERE $timeFilter",
     "select": [
      [
       {
        "params": [
         "/docter_agent:docter_agent/health/route_availability"
        ],
        "type": "field"
       },
       { "params": [ "route_availability" ], "type": "alias" }
      ],
      [
       {
        "params": [
         "/docter_agent:docter_agent/health/route_status"
        ],
        "type": "field"
       },
       { "params": [ "route_status" ], "type": "alias" }
      ],
      [
       {
        "params": [
         "/docter_agent:docter_agent/reports/events_name"
        ],
        "type": "field"
       },
       { "params": [ "events_name" ], "type": "alias" }
      ],
      [
       {
        "params": [
         "/docter_agent:docter_agent/reports/events_sample-period"
        ],
        "type": "field"
       },
       { "params": [ "events_sample-period" ], "type": "alias" }
      ],
      [
       {
        "params": [
         "/docter_agent:docter_agent/reports/events_timestamp"
        ],
        "type": "field"
       },
       { "params": [ "events_timestamp" ], "type": "alias" }
      ],
      [
       {
        "params": [
         "/docter_agent:docter_agent/reports/events_trigger"
        ],
        "type": "field"
       },
       { "params": [ "events_trigger" ], "type": "alias" }
      ],
      [
       {
        "params": [
         "/docter_agent:docter_agent/reports/events_values_0"
        ],
        "type": "field"
       },
       { "params": [ "events_values_0" ], "type": "alias" }
      ],
      [
       {
        "params": [
         "/docter_agent:docter_agent/reports/events_values_1"
        ],
        "type": "field"
       },
       { "params": [ "events_values_1" ], "type": "alias" }
      ],
      [
       {
        "params": [
         "/docter_agent:docter_agent/reports/events_values_2"
        ],
        "type": "field"
       },
       { "params": [ "events_values2" ], "type": "alias" }
      ],
      [
       {
        "params": [
         "/docter_agent:docter_agent/reports/history/path/event_v"
        ],
        "type": "field"
       },
       { "params": [ "event_v" ], "type": "alias" }
      ],
      [
       {
        "params": [
         "/docter_agent:docter_agent/reports_count"
        ],
        "type": "field"
       },
       { "params": [ "reports_count" ], "type": "alias" }
      ],
      [
       {
        "params": [
         "/docter_agent:docter_agent/reports_filtered"
        ],
        "type": "field"
       },
       { "params": [ "reports_filtered" ], "type": "alias" }
      ],
      [
       {
        "params": [
         "/docter_agent:docter_agent/reports_last-updated"
        ],
        "type": "field"
       },
       { "params": [ "reports_last-updated" ], "type": "alias" }
      ]
     ]
    }
   ]
  }
 ]
}