{
 "title": "Custom Agent CPU Monitoring",
 "time": { "from": "now-5m", "to": "now" },
 "refresh": "10s",
 "panels": [
  {
   "title": "SR Linux On change CPU Custom Threshold (80%) Monitoring",
   "type": "state-timeline",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "string" } },
   "targets": [
    {
     "alias": "$tag_source",
     "groupBy": [
      { "params": [ "source" ], "type": "tag" }
     ],
     "measurement": "SRL_docter-agent-cpu",
     "select": [
      [
       {
        "params": [
         "/docter_agent:docter_agent/metrics/metric_status"
        ],
        "type": "field"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Latest Status",
   "type": "table",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "targets": [
    {
     "measurement": "SRL_docter-agent-cpu",
     "query": "SELECT \"source\" AS \"Node\", \"/docter_agent:docter_agent/metrics/metric_status-summary\" AS \"Status\" FROM \"SRL_docter-agent-cpu\" WHERE $timeFilter limit 3",
     "select": [
      [
       {
        "params": [
         "/docter_agent:docter_agent/metrics/metric_status-summary"
        ],
        "type": "field"
       },
       { "params": [ "Status" ], "type": "alias" }
      ]
     ]
    }
   ]
  },
  {
   "title": "Traditional Monitoring",
   "type": "graph",
   "gridPos": { "h": 12, "w": 12, "x": 0, "y": 8 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "expr": "gnmic_srl_cpu_instant", "legendFormat": "{{source}}" }
   ]
  },
  {
   "title": "Status History",
   "type": "table",
   "gridPos": { "h": 12, "w": 12, "x": 12, "y": 8 },
   "targets": [
    {
     "measurement": "SRL_docter-agent-cpu",
     "query": "SELECT \"source\" AS \"Node\",  \"/docter_agent:docter_agent/metrics/metric_status-summary\" AS \"Consolidated State\" FROM \"SRL_docter-agent-cpu\" WHERE $timeFilter",
     "select": [
      [
       {
        "params": [
         "/docter_agent:docter_agent/metrics/metric_cause"
        ],
        "type": "field"
       },
       { "params": [ "Cause" ], "type": "alias" }
      ],
      [
       {
        "params": [
         "/docter_agent:docter_agent/metrics/metric/contribution_status"
        ],
        "type": "field"
       },
       { "params": [ "Status" ], "type": "alias" }
      ],
      [
       {
        "params": [
         "/docter_agent:docter_agent/metrics/metric_status-summary"
        ],
        "type": "field"
       },
       { "params": [ "Status" ], "type": "alias" }
      ]
     ]
    }
   ]
  }
 ]
}