{
 "title": "Demo Dashboard",
 "time": { "from": "now-15m", "to": "now" },
 "refresh": "5s",
 "templating": {
  "list": [
   { "name": "NE", "query": "label_values(source)" }
  ]
 },
 "panels": [
  {
   "title": "Docter Agent Value",
   "type": "table",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "gnmic_srl_docter_agent_value{source=\"$NE\"}"
    }
   ]
  },
  {
   "title": "Link Bandwidth",
   "type": "agenty-flowcharting-panel",
   "gridPos": { "h": 21, "w": 12, "x": 12, "y": 0 },
   "format": "short",
   "valueName": "current",
   "targets": [
    {
     "expr": "irate(gnmic_srl_if_stats_out_octets[30s])*8",
     "legendFormat": "{{source}}:{{interface_name}}:out"
    },
    {
     "expr": "irate(gnmic_srl_if_stats_in_octets[30s])*8",
     "legendFormat": "{{source}}:{{interface_name}}:in"
    }
   ]
  },
  {
   "title": "Docter Agent Reports",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "gnmic_srl_docter_agent_count{source=\"$NE\"}"
    }
   ]
  },
  {
   "title": "Throughput e-1/1",
   "type": "graph",
   "gridPos": { "h": 10, "w": 4, "x": 0, "y": 16 },
   "yaxes": [
    { "format": "bps" }
   ],
   "targets": [
    {
     "expr": "rate(gnmic_srl_if_stats_in_octets{source=\"$NE\",interface_name=\"ethernet-1/1\"}[30s])*8",
     "legendFormat": "ethernet-1/1 IN"
    },
    {
     "expr": "-rate(gnmic_srl_if_stats_out_octets{source=\"$NE\",interface_name=\"ethernet-1/1\"}[30s])*8",
     "legendFormat": "ethernet-1/1 OUT"
    }
   ]
  },
  {
   "title": "Throughput e-1/2",
   "type": "graph",
   "gridPos": { "h": 10, "w": 4, "x": 4, "y": 16 },
   "yaxes": [
    { "format": "bps" }
   ],
   "targets": [
    {
     "expr": "rate(gnmic_srl_if_stats_in_octets{source=\"$NE\",interface_name=\"ethernet-1/1\"}[30s])*8",
     "legendFormat": "ethernet-1/1 IN"
    },
    {
     "expr": "-rate(gnmic_srl_if_stats_out_octets{source=\"$NE\",interface_name=\"ethernet-1/1\"}[30s])*8",
     "legendFormat": "ethernet-1/1 OUT"
    }
   ]
  },
  {
   "title": "Throughput e-1/3",
   "type": "graph",
   "gridPos": { "h": 10, "w": 4, "x": 8, "y": 16 },
   "yaxes": [
    { "format": "bps" }
   ],
   "targets": [
    {
     "expr": "rate(gnmic_srl_if_stats_in_octets{source=\"$NE\",interface_name=\"ethernet-1/3\"}[30s])*8",
     "legendFormat": "ethernet-1/1 IN"
    },
    {
     "expr": "-rate(gnmic_srl_if_stats_out_octets{source=\"$NE\",interface_name=\"ethernet-1/3\"}[30s])*8",
     "legendFormat": "ethernet-1/1 OUT"
    }
   ]
  },
  {
   "title": "Throughput e-1/36",
   "type": "graph",
   "gridPos": { "h": 11, "w": 6, "x": 0, "y": 26 },
   "yaxes": [
    { "format": "bps" }
   ],
   "targets": [
    {
     "expr": "rate(gnmic_srl_if_stats_in_octets{source=\"$NE\",interface_name=\"ethernet-1/36\"}[30s])*8",
     "legendFormat": "ethernet-1/1 IN"
    },
    {
     "expr": "-rate(gnmic_srl_if_stats_out_octets{source=\"$NE\",interface_name=\"ethernet-1/36\"}[30s])*8",
     "legendFormat": "ethernet-1/1 OUT"
    }
   ]
  },
  {
   "title": "CPU",
   "type": "graph",
   "gridPos": { "h": 11, "w": 6, "x": 6, "y": 26 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "expr": "gnmic_srl_cpu_instant{source=\"$NE\"}",
     "legendFormat": "Total Instant"
    },
    {
     "expr": "gnmic_srl_mem_free{source=\"$NE\"}",
     "legendFormat": "Mem Free"
    }
   ]
  },
  {
   "title": "IPv4 Routing Stats",
   "type": "stat",
   "gridPos": { "h": 5, "w": 6, "x": 0, "y": 37 },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "gnmic_srl_ipv4_routes_active_routes{network_instance_name=\"default\",source=\"$NE\"}",
     "legendFormat": "Active Routes"
    },
    {
     "expr": "gnmic_srl_ipv4_routes_total_routes{network_instance_name=\"default\",source=\"$NE\"}",
     "legendFormat": "Total Routes"
    },
    {
     "expr": "gnmic_srl_ipv4_routes_active_routes_with_ecmp{network_instance_name=\"default\",source=\"$NE\"}",
     "legendFormat": "Active ECMP Routes"
    }
   ]
  },
  {
   "title": "BGP Peer stats",
   "type": "stat",
   "gridPos": { "h": 5, "w": 6, "x": 6, "y": 37 },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "gnmic_srl_bgp_stats_up_peers{network_instance_name=\"default\",source=\"$NE\"}",
     "legendFormat": "Up Peers"
    },
    {
     "expr": "gnmic_srl_bgp_stats_total_peers{network_instance_name=\"default\",source=\"$NE\"}",
     "legendFormat": "Total Peers"
    },
    {
     "expr": "gnmic_srl_bgp_stats_disabled_peers{network_instance_name=\"default\",source=\"$NE\"}",
     "legendFormat": "Disabled Peers"
    }
   ]
  },
  {
   "title": "IPv6 Routing Stats",
   "type": "stat",
   "gridPos": { "h": 5, "w": 6, "x": 0, "y": 42 },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "gnmic_srl_ipv6_routes_active_routes{network_instance_name=\"default\",source=\"$NE\"}",
     "legendFormat": "Active Routes"
    },
    {
     "expr": "gnmic_srl_ipv6_routes_total_routes{network_instance_name=\"default\",source=\"$NE\"}",
     "legendFormat": "Total Routes"
    },
    {
     "expr": "gnmic_srl_ipv6_routes_active_routes_with_ecmp{network_instance_name=\"default\",source=\"$NE\"}",
     "legendFormat": "Active ECMP Routes"
    }
   ]
  },
  {
   "title": "BGP Route Stats",
   "type": "stat",
   "gridPos": { "h": 5, "w": 6, "x": 6, "y": 42 },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "gnmic_srl_bgp_stats_total_received_routes{network_instance_name=\"default\",source=\"$NE\"}",
     "legendFormat": "Total Received Routes"
    },
    {
     "expr": "gnmic_srl_bgp_stats_total_active_routes{network_instance_name=\"default\",source=\"$NE\"}",
     "legendFormat": "Total Active Routes"
    }
   ]
  }
 ]
}