{
 "title": "All",
 "time": { "from": "now-5m", "to": "now" },
 "refresh": "5s",
 "templating": {
  "list": [
   {
    "name": "srl_name",
    "label": "srl_name",
    "query": "SELECT distinct(\"srl_nokia_system:system/srl_nokia_system_name:name_host-name\") FROM \"SRL_all\""
   }
  ]
 },
 "panels": [
  {
   "title": "CPU Total",
   "type": "gauge",
   "gridPos": { "h": 6, "w": 5, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "alias": "CPU Total",
     "measurement": "SRL_all",
     "select": [
      [
       {
        "params": [
         "srl_nokia_platform:platform/srl_nokia_platform_control:control/srl_nokia_platform_cpu:cpu/total_instant"
        ],
        "type": "field"
       }
      ]
     ],
     "tags": [
      { "key": "source", "operator": "=~", "value": "/^$srl_name$/" }
     ]
    }
   ]
  },
  {
   "title": "Memory Utilization",
   "type": "heatmap",
   "gridPos": { "h": 6, "w": 7, "x": 5, "y": 0 },
   "targets": [
    {
     "alias": "Memory Utilization",
     "measurement": "SRL_all",
     "select": [
      [
       {
        "params": [
         "srl_nokia_platform:platform/srl_nokia_platform_control:control/srl_nokia_platform_memory:memory_utilization"
        ],
        "type": "field"
       }
      ]
     ],
     "tags": [
      { "key": "source", "operator": "=~", "value": "/^$srl_name$/" }
     ]
    }
   ]
  },
  {
   "title": "SRL Info",
   "type": "table",
   "gridPos": { "h": 4, "w": 12, "x": 12, "y": 0 },
   "targets": [
    {
     "measurement": "SRL_all",
     "query": "SELECT last(\"srl_nokia_system_name:name_host-name\") AS \"hostname\", last(\"srl_nokia_system_info:information_uptime\") AS \"uptime\", last(\"srl_nokia_system_info:information_version\") AS \"version\" FROM \"SRL_system\" WHERE (\"source\" =~ /^$srl_name$/) AND $timeFilter ",
     "select": [
      [
       {
        "params": [
         "srl_nokia_system:system/srl_nokia_system_name:name_host-name"
        ],
        "type": "field"
       },
       {
        "params": [],
        "type": "last"
       },
       { "params": [ "hostname" ], "type": "alias" }
      ],
      [
       {
        "params": [
         "srl_nokia_platform:platform/srl_nokia_platform_chassis:chassis_type"
        ],
        "type": "field"
       },
       {
        "params": [],
        "type": "last"
       },
       { "params": [ "chassis" ], "type": "alias" }
      ],
      [
       {
        "params": [
         "srl_nokia_system:system/srl_nokia_system_info:information_version"
        ],
        "type": "field"
       },
       {
        "params": [],
        "type": "last"
       },
       { "params": [ "version" ], "type": "alias" }
      ],
      [
       {
        "params": [
         "srl_nokia_system:system/srl_nokia_system_info:information_uptime"
        ],
        "type": "field"
       },
       {
        "params": [],
        "type": "last"
       },
       { "params": [ "uptime" ], "type": "alias" }
      ],
      [
       {
        "params": [
         "srl_nokia_system:system/srl_nokia_configuration:configuration_last-change"
        ],
        "type": "field"
       },
       {
        "params": [],
        "type": "last"
       },
       { "params": [ "config-change" ], "type": "alias" }
      ]
     ],
     "tags": [
      { "key": "source", "operator": "=~", "value": "/^$srl_name$/" }
     ]
    }
   ]
  },
  {
   "title": "SRL LLDP",
   "type": "table",
   "gridPos": { "h": 4, "w": 12, "x": 12, "y": 4 },
   "targets": [
    {
     "groupBy": [
      { "params": [ "name" ], "type": "tag" }
     ],
     "measurement": "SRL_all",
     "select": [
      [
       {
        "params": [
         "srl_nokia_system:system/srl_nokia_lldp:lldp/interface/neighbor_system-name"
        ],
        "type": "field"
       },
       {
        "params": [],
        "type": "last"
       },
       { "params": [ "neighbor name" ], "type": "alias" }
      ],
      [
       {
        "params": [
         "srl_nokia_system:system/srl_nokia_lldp:lldp/interface/neighbor_port-id"
        ],
        "type": "field"
       },
       {
        "params": [],
        "type": "last"
       },
       { "params": [ "neighbor port" ], "type": "alias" }
      ]
     ],
     "tags": [
      { "key": "source", "operator": "=~", "value": "/^$srl_name$/" }
     ]
    }
   ]
  },
  {
   "title": "BGP Neighbor Status",
   "type": "flant-statusmap-panel",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 6 },
   "targets": [
    {
     "groupBy": [
      { "params": [ "peer_address" ], "type": "tag" }
     ],
     "measurement": "SRL_all",
     "select": [
      [
       {
        "params": [
         "srl_nokia_network_instance:network_instance/protocols/srl_nokia_bgp:bgp/neighbor_session-state"
        ],
        "type": "field"
       },
       { "params": [ "neighor" ], "type": "alias" }
      ]
     ],
     "tags": [
      { "key": "source", "operator": "=~", "value": "/^$srl_name$/" }
     ]
    }
   ]
  },
  {
   "title": "SRL BGP",
   "type": "table",
   "gridPos": { "h": 4, "w": 12, "x": 12, "y": 8 },
   "targets": [
    {
     "groupBy": [
      { "params": [ "peer_address" ], "type": "tag" }
     ],
     "measurement": "SRL_all",
     "select": [
      [
       {
        "params": [
         "srl_nokia_network_instance:network_instance/protocols/srl_nokia_bgp:bgp/neighbor_session-state"
        ],
        "type": "field"
       },
       {
        "params": [],
        "type": "last"
       },
       { "params": [ "state" ], "type": "alias" }
      ],
      [
       {
        "params": [
         "srl_nokia_network_instance:network_instance/protocols/srl_nokia_bgp:bgp/neighbor_peer-as"
        ],
        "type": "field"
       },
       { "params": [ "peer_as" ], "type": "alias" }
      ],
      [
       {
        "params": [
         "srl_nokia_network_instance:network_instance/protocols/srl_nokia_bgp:bgp/neighbor/ipv4_unicast_sent-routes"
        ],
        "type": "field"
       },
       { "params": [ "ipv4 advertised" ], "type": "alias" }
      ],
      [
       { "params": [ "bgp:bgp" ], "type": "field" },
       { "params": [ "ipv4 received" ], "type": "alias" }
      ]
     ],
     "tags": [
      { "key": "source", "operator": "=~", "value": "/^$srl_name$/" }
     ]
    }
   ]
  },
  {
   "title": "SRL Apps",
   "type": "flant-statusmap-panel",
   "gridPos": { "h": 14, "w": 12, "x": 0, "y": 12 },
   "targets": [
    {
     "alias": "aaa_mgr",
     "measurement": "SRL_all",
     "query": "SELECT \"srl_nokia_app_mgmt:app_management/application_state\" FROM \"SRL_system\" WHERE (\"name\" = 'aaa_mgr') AND $timeFilter",
     "select": [
      [
       {
        "params": [
         "srl_nokia_system:system/srl_nokia_app_mgmt:app_management/application_state"
        ],
        "type": "field"
       }
      ]
     ],
     "tags": [
      { "key": "name", "operator": "=", "value": "aaa_mgr" },
      { "condition": "AND", "key": "source", "operator": "=~", "value": "/^$srl_name$/" }
     ]
    },
    {
     "alias": "acl_mgr",
     "measurement": "SRL_all",
     "query": "SELECT \"srl_nokia_app_mgmt:app_management/application_state\" FROM \"SRL_system\" WHERE (\"name\" = 'acl_mgr') AND $timeFilter",
     "select": [
      [
       {
        "params": [
         "srl_nokia_system:system/srl_nokia_app_mgmt:app_management/application_state"
        ],
        "type": "field"
       }
      ]
     ],
     "tags": [
      { "key": "name", "operator": "=", "value": "acl_mgr" },
      { "condition": "AND", "key": "source", "operator": "=~", "value": "/^$srl_name$/" }
     ]
    },
    {
     "alias": "app_mgr",
     "measurement": "SRL_all",
     "query": "SELECT \"srl_nokia_app_mgmt:app_management/application_state\" FROM \"SRL_system\" WHERE (\"name\" = 'app_mgr') AND $timeFilter",
     "select": [
      [
       {
        "params": [
         "srl_nokia_system:system/srl_nokia_app_mgmt:app_management/application_state"
        ],
        "type": "field"
       }
      ]
     ],
     "tags": [
      { "key": "name", "operator": "=", "value": "app_mgr" },
      { "condition": "AND", "key": "source", "operator": "=~", "value": "/^$srl_name$/" }
     ]
    },
    {
     "alias": "arp_nd_mgr",
     "measurement": "SRL_all",
     "query": "SELECT \"srl_nokia_app_mgmt:app_management/application_state\" FROM \"SRL_system\" WHERE (\"name\" = 'arp_nd_mgr') AND $timeFilter",
     "select": [
      [
       {
        "params": [
         "srl_nokia_system:system/srl_nokia_app_mgmt:app_management/application_state"
        ],
        "type": "field"
       }
      ]
     ],
     "tags": [
      { "key": "name", "operator": "=", "value": "arp_nd_mgr" },
      { "condition": "AND", "key": "source", "operator": "=~", "value": "/^$srl_name$/" }
     ]
    },
    {
     "alias": "bfd_mgr",
     "measurement": "SRL_all",
     "query": "SELECT \"srl_nokia_app_mgmt:app_management/application_state\" FROM \"SRL_system\" WHERE (\"name\" = 'bfd_mgr') AND $timeFilter",
     "select": [
      [
       {
        "params": [
         "srl_nokia_system:system/srl_nokia_app_mgmt:app_management/application_state"
        ],
        "type": "field"
       }
      ]
     ],
     "tags": [
      { "key": "name", "operator": "=", "value": "bfd_mgr" },
      { "condition": "AND", "key": "source", "operator": "=~", "value": "/^$srl_name$/" }
     ]
    },
    {
     "alias": "fib_agent",
     "measurement": "SRL_all",
     "query": "SELECT \"srl_nokia_app_mgmt:app_management/application_state\" FROM \"SRL_system\" WHERE (\"name\" = 'bgp_mgr') AND $timeFilter",
     "select": [
      [
       {
        "params": [
         "srl_nokia_system:system/srl_nokia_app_mgmt:app_management/application_state"
        ],
        "type": "field"
       }
      ]
     ],
     "tags": [
      { "key": "name", "operator": "=", "value": "fib_agent" },
      { "condition": "AND", "key": "source", "operator": "=~", "value": "/^$srl_name$/" }
     ]
    },
    {
     "alias": "chassis_mgr",
     "measurement": "SRL_all",
     "query": "SELECT \"srl_nokia_app_mgmt:app_management/application_state\" FROM \"SRL_system\" WHERE (\"name\" = 'chassis_mgr') AND $timeFilter",
     "select": [
      [
       {
        "params": [
         "srl_nokia_system:system/srl_nokia_app_mgmt:app_management/application_state"
        ],
        "type": "field"
       }
      ]
     ],
     "tags": [
      { "key": "name", "operator": "=", "value": "chassis_mgr" },
      { "condition": "AND", "key": "source", "operator": "=~", "value": "/^$srl_name$/" }
     ]
    },
    {
     "alias": "dev_mgr",
     "measurement": "SRL_all",
     "query": "SELECT \"srl_nokia_app_mgmt:app_management/application_state\" FROM \"SRL_system\" WHERE (\"name\" = 'dev_mgr') AND $timeFilter",
     "select": [
      [
       {
        "params": [
         "srl_nokia_system:system/srl_nokia_app_mgmt:app_management/application_state"
        ],
        "type": "field"
       }
      ]
     ],
     "tags": [
      { "key": "name", "operator": "=", "value": "dev_mgr" },
      { "condition": "AND", "key": "source", "operator": "=~", "value": "/^$srl_name$/" }
     ]
    },
    {
     "alias": "dhcp_client_mgr",
     "measurement": "SRL_all",
     "query": "SELECT \"srl_nokia_app_mgmt:app_management/application_state\" FROM \"SRL_system\" WHERE (\"name\" = 'dhcp_client_mgr') AND $timeFilter",
     "select": [
      [
       {
        "params": [
         "srl_nokia_system:system/srl_nokia_app_mgmt:app_management/application_state"
        ],
        "type": "field"
       }
      ]
     ],
     "tags": [
      { "key": "name", "operator": "=", "value": "dhcp_client_mgr" },
      { "condition": "AND", "key": "source", "operator": "=~", "value": "/^$srl_name$/" }
     ]
    },
    {
     "alias": "fib_mgr",
     "measurement": "SRL_all",
     "query": "SELECT \"srl_nokia_app_mgmt:app_management/application_state\" FROM \"SRL_system\" WHERE (\"name\" = 'fib_mgr') AND $timeFilter",
     "select": [
      [
       {
        "params": [
         "srl_nokia_system:system/srl_nokia_app_mgmt:app_management/application_state"
        ],
        "type": "field"
       }
      ]
     ],
     "tags": [
      { "key": "name", "operator": "=", "value": "fib_mgr" },
      { "condition": "AND", "key": "source", "operator": "=~", "value": "/^$srl_name$/" }
     ]
    },
    {
     "alias": "gnmi_server",
     "measurement": "SRL_all",
     "query": "SELECT \"srl_nokia_app_mgmt:app_management/application_state\" FROM \"SRL_system\" WHERE (\"name\" = 'gnmi_server') AND $timeFilter",
     "select": [
      [
       {
        "params": [
         "srl_nokia_system:system/srl_nokia_app_mgmt:app_management/application_state"
        ],
        "type": "field"
       }
      ]
     ],
     "tags": [
      { "key": "name", "operator": "=", "value": "gnmi_server" },
      { "condition": "AND", "key": "source", "operator": "=~", "value": "/^$srl_name$/" }
     ]
    },
    {
     "alias": "idb_server",
     "measurement": "SRL_all",
     "query": "SELECT \"srl_nokia_app_mgmt:app_management/application_state\" FROM \"SRL_system\" WHERE (\"name\" = 'idb_server') AND $timeFilter",
     "select": [
      [
       {
        "params": [
         "srl_nokia_system:system/srl_nokia_app_mgmt:app_management/application_state"
        ],
        "type": "field"
       }
      ]
     ],
     "tags": [
      { "key": "name", "operator": "=", "value": "idb_server" },
      { "condition": "AND", "key": "source", "operator": "=~", "value": "/^$srl_name$/" }
     ]
    },
    {
     "alias": "isis_mgr",
     "measurement": "SRL_all",
     "query": "SELECT \"srl_nokia_app_mgmt:app_management/application_state\" FROM \"SRL_system\" WHERE (\"name\" = 'idb_server') AND $timeFilter",
     "select": [
      [
       {
        "params": [
         "srl_nokia_system:system/srl_nokia_app_mgmt:app_management/application_state"
        ],
        "type": "field"
       }
      ]
     ],
     "tags": [
      { "key": "name", "operator": "=", "value": "isis_mgr" },
      { "condition": "AND", "key": "source", "operator": "=~", "value": "/^$srl_name$/" }
     ]
    },
    {
     "alias": "json_rpc",
     "measurement": "SRL_all",
     "query": "SELECT \"srl_nokia_app_mgmt:app_management/application_state\" FROM \"SRL_system\" WHERE (\"name\" = 'json_rpc') AND $timeFilter",
     "select": [
      [
       {
        "params": [
         "srl_nokia_system:system/srl_nokia_app_mgmt:app_management/application_state"
        ],
        "type": "field"
       }
      ]
     ],
     "tags": [
      { "key": "name", "operator": "=", "value": "json_rpc" },
      { "condition": "AND", "key": "source", "operator": "=~", "value": "/^$srl_name$/" }
     ]
    },
    {
     "alias": "l2_mac_learn_mgr",
     "measurement": "SRL_all",
     "query": "SELECT \"srl_nokia_app_mgmt:app_management/application_state\" FROM \"SRL_system\" WHERE (\"name\" = 'linux_mgr') AND $timeFilter",
     "select": [
      [
       {
        "params": [
         "srl_nokia_system:system/srl_nokia_app_mgmt:app_management/application_state"
        ],
        "type": "field"
       }
      ]
     ],
     "tags": [
      { "key": "name", "operator": "=", "value": "l2_mac_learn_mgr" },
      { "condition": "AND", "key": "source", "operator": "=~", "value": "/^$srl_name$/" }
     ]
    },
    {
     "alias": "l2_mac_mgr",
     "measurement": "SRL_all",
     "query": "SELECT \"srl_nokia_app_mgmt:app_management/application_state\" FROM \"SRL_system\" WHERE (\"name\" = 'lldp_mgr') AND $timeFilter",
     "select": [
      [
       {
        "params": [
         "srl_nokia_system:system/srl_nokia_app_mgmt:app_management/application_state"
        ],
        "type": "field"
       }
      ]
     ],
     "tags": [
      { "key": "name", "operator": "=", "value": "l2_mac_mgr" },
      { "condition": "AND", "key": "source", "operator": "=~", "value": "/^$srl_name$/" }
     ]
    },
    {
     "alias": "l2_static_mac_mgr",
     "measurement": "SRL_all",
     "query": "SELECT \"srl_nokia_app_mgmt:app_management/application_state\" FROM \"SRL_system\" WHERE (\"name\" = 'log_mgr') AND $timeFilter",
     "select": [
      [
       {
        "params": [
         "srl_nokia_system:system/srl_nokia_app_mgmt:app_management/application_state"
        ],
        "type": "field"
       }
      ]
     ],
     "tags": [
      { "key": "name", "operator": "=", "value": "l2_static_mac_mgr" },
      { "condition": "AND", "key": "source", "operator": "=~", "value": "/^$srl_name$/" }
     ]
    },
    {
     "alias": "lag_mgr",
     "measurement": "SRL_all",
     "query": "SELECT \"srl_nokia_app_mgmt:app_management/application_state\" FROM \"SRL_system\" WHERE (\"name\" = 'mgmt_server') AND $timeFilter",
     "select": [
      [
       {
        "params": [
         "srl_nokia_system:system/srl_nokia_app_mgmt:app_management/application_state"
        ],
        "type": "field"
       }
      ]
     ],
     "tags": [
      { "key": "name", "operator": "=", "value": "lag_mgr" },
      { "condition": "AND", "key": "source", "operator": "=~", "value": "/^$srl_name$/" }
     ]
    },
    {
     "alias": "linux_mgr",
     "measurement": "SRL_all",
     "query": "SELECT \"srl_nokia_app_mgmt:app_management/application_state\" FROM \"SRL_system\" WHERE (\"name\" = 'mpls_mgr') AND $timeFilter",
     "select": [
      [
       {
        "params": [
         "srl_nokia_system:system/srl_nokia_app_mgmt:app_management/application_state"
        ],
        "type": "field"
       }
      ]
     ],
     "tags": [
      { "key": "name", "operator": "=", "value": "linux_mgr" },
      { "condition": "AND", "key": "source", "operator": "=~", "value": "/^$srl_name$/" }
     ]
    },
    {
     "alias": "lldp_mgr",
     "measurement": "SRL_all",
     "query": "SELECT \"srl_nokia_app_mgmt:app_management/application_state\" FROM \"SRL_system\" WHERE (\"name\" = 'net_inst_mgr') AND $timeFilter",
     "select": [
      [
       {
        "params": [
         "srl_nokia_system:system/srl_nokia_app_mgmt:app_management/application_state"
        ],
        "type": "field"
       }
      ]
     ],
     "tags": [
      { "key": "name", "operator": "=", "value": "lldp_mgr" },
      { "condition": "AND", "key": "source", "operator": "=~", "value": "/^$srl_name$/" }
     ]
    },
    {
     "alias": "log_mgr",
     "measurement": "SRL_all",
     "query": "SELECT \"srl_nokia_app_mgmt:app_management/application_state\" FROM \"SRL_system\" WHERE (\"name\" = 'oam_mgr') AND $timeFilter",
     "select": [
      [
       {
        "params": [
         "srl_nokia_system:system/srl_nokia_app_mgmt:app_management/application_state"
        ],
        "type": "field"
       }
      ]
     ],
     "tags": [
      { "key": "name", "operator": "=", "value": "log_mgr" },
      { "condition": "AND", "key": "source", "operator": "=~", "value": "/^$srl_name$/" }
     ]
    },
    {
     "alias": "mcid_mgr",
     "measurement": "SRL_all",
     "query": "SELECT \"srl_nokia_app_mgmt:app_management/application_state\" FROM \"SRL_system\" WHERE (\"name\" = 'plcy_mgr') AND $timeFilter",
     "select": [
      [
       {
        "params": [
         "srl_nokia_system:system/srl_nokia_app_mgmt:app_management/application_state"
        ],
        "type": "field"
       }
      ]
     ],
     "tags": [
      { "key": "name", "operator": "=", "value": "mcid_mgr" },
      { "condition": "AND", "key": "source", "operator": "=~", "value": "/^$srl_name$/" }
     ]
    },
    {
     "alias": "mgmt_server",
     "measurement": "SRL_all",
     "query": "SELECT \"srl_nokia_app_mgmt:app_management/application_state\" FROM \"SRL_system\" WHERE (\"name\" = 'qos_mgr') AND $timeFilter",
     "select": [
      [
       {
        "params": [
         "srl_nokia_system:system/srl_nokia_app_mgmt:app_management/application_state"
        ],
        "type": "field"
       }
      ]
     ],
     "tags": [
      { "key": "name", "operator": "=", "value": "mgmt_server" },
      { "condition": "AND", "key": "source", "operator": "=~", "value": "/^$srl_name$/" }
     ]
    },
    {
     "alias": "mpls_mgr",
     "measurement": "SRL_all",
     "query": "SELECT \"srl_nokia_app_mgmt:app_management/application_state\" FROM \"SRL_system\" WHERE (\"name\" = 'sdk_mgr') AND $timeFilter",
     "select": [
      [
       {
        "params": [
         "srl_nokia_system:system/srl_nokia_app_mgmt:app_management/application_state"
        ],
        "type": "field"
       }
      ]
     ],
     "tags": [
      { "key": "name", "operator": "=", "value": "mpls_mgr" },
      { "condition": "AND", "key": "source", "operator": "=~", "value": "/^$srl_name$/" }
     ]
    },
    {
     "alias": "net_inst_mgr",
     "measurement": "SRL_all",
     "query": "SELECT \"srl_nokia_app_mgmt:app_management/application_state\" FROM \"SRL_system\" WHERE (\"name\" = 'xdp_lc_1') AND $timeFilter",
     "select": [
      [
       {
        "params": [
         "srl_nokia_system:system/srl_nokia_app_mgmt:app_management/application_state"
        ],
        "type": "field"
       }
      ]
     ],
     "tags": [
      { "key": "name", "operator": "=", "value": "net_inst_mgr" },
      { "condition": "AND", "key": "source", "operator": "=~", "value": "/^$srl_name$/" }
     ]
    },
    {
     "alias": "oam_mgr",
     "measurement": "SRL_all",
     "query": "SELECT \"srl_nokia_app_mgmt:app_management/application_state\" FROM \"SRL_system\" WHERE (\"name\" = 'sshd-mgmt') AND $timeFilter",
     "select": [
      [
       {
        "params": [
         "srl_nokia_system:system/srl_nokia_app_mgmt:app_management/application_state"
        ],
        "type": "field"
       }
      ]
     ],
     "tags": [
      { "key": "name", "operator": "=", "value": "oam_mgr" },
      { "condition": "AND", "key": "source", "operator": "=~", "value": "/^$srl_name$/" }
     ]
    },
    {
     "alias": "ospf_mgr",
     "measurement": "SRL_all",
     "query": "SELECT \"srl_nokia_app_mgmt:app_management/application_state\" FROM \"SRL_system\" WHERE (\"name\" = 'static_route_mgr') AND $timeFilter",
     "select": [
      [
       {
        "params": [
         "srl_nokia_system:system/srl_nokia_app_mgmt:app_management/application_state"
        ],
        "type": "field"
       }
      ]
     ],
     "tags": [
      { "key": "name", "operator": "=", "value": "ospf_mgr" },
      { "condition": "AND", "key": "source", "operator": "=~", "value": "/^$srl_name$/" }
     ]
    },
    {
     "alias": "plcy_mgr",
     "measurement": "SRL_all",
     "query": "SELECT \"srl_nokia_app_mgmt:app_management/application_state\" FROM \"SRL_system\" WHERE (\"name\" = 'supportd') AND $timeFilter",
     "select": [
      [
       {
        "params": [
         "srl_nokia_system:system/srl_nokia_app_mgmt:app_management/application_state"
        ],
        "type": "field"
       }
      ]
     ],
     "tags": [
      { "key": "name", "operator": "=", "value": "plcy_mgr" },
      { "condition": "AND", "key": "source", "operator": "=~", "value": "/^$srl_name$/" }
     ]
    },
    {
     "alias": "qos_mgr",
     "measurement": "SRL_all",
     "query": "SELECT \"srl_nokia_app_mgmt:app_management/application_state\" FROM \"SRL_system\" WHERE (\"name\" = 'xdp_cpm') AND $timeFilter",
     "select": [
      [
       {
        "params": [
         "srl_nokia_system:system/srl_nokia_app_mgmt:app_management/application_state"
        ],
        "type": "field"
       }
      ]
     ],
     "tags": [
      { "key": "name", "operator": "=", "value": "qos_mgr" },
      { "condition": "AND", "key": "source", "operator": "=~", "value": "/^$srl_name$/" }
     ]
    },
    {
     "alias": "sdk_mgr",
     "measurement": "SRL_all",
     "query": "SELECT \"srl_nokia_app_mgmt:app_management/application_state\" FROM \"SRL_system\" WHERE (\"name\" = 'xdp_cpm') AND $timeFilter",
     "select": [
      [
       {
        "params": [
         "srl_nokia_system:system/srl_nokia_app_mgmt:app_management/application_state"
        ],
        "type": "field"
       }
      ]
     ],
     "tags": [
      { "key": "name", "operator": "=", "value": "sdk_mgr" },
      { "condition": "AND", "key": "source", "operator": "=~", "value": "/^$srl_name$/" }
     ]
    },
    {
     "alias": "sshd-mgmt",
     "measurement": "SRL_all",
     "query": "SELECT \"srl_nokia_app_mgmt:app_management/application_state\" FROM \"SRL_system\" WHERE (\"name\" = 'xdp_cpm') AND $timeFilter",
     "select": [
      [
       {
        "params": [
         "srl_nokia_system:system/srl_nokia_app_mgmt:app_management/application_state"
        ],
        "type": "field"
       }
      ]
     ],
     "tags": [
      { "key": "name", "operator": "=", "value": "sshd-mgmt" },
      { "condition": "AND", "key": "source", "operator": "=~", "value": "/^$srl_name$/" }
     ]
    },
    {
     "alias": "static_route_mgr",
     "measurement": "SRL_all",
     "query": "SELECT \"srl_nokia_app_mgmt:app_management/application_state\" FROM \"SRL_system\" WHERE (\"name\" = 'xdp_cpm') AND $timeFilter",
     "select": [
      [
       {
        "params": [
         "srl_nokia_system:system/srl_nokia_app_mgmt:app_management/application_state"
        ],
        "type": "field"
       }
      ]
     ],
     "tags": [
      { "key": "name", "operator": "=", "value": "static_route_mgr" },
      { "condition": "AND", "key": "source", "operator": "=~", "value": "/^$srl_name$/" }
     ]
    },
    {
     "alias": "supportd",
     "measurement": "SRL_all",
     "query": "SELECT \"srl_nokia_app_mgmt:app_management/application_state\" FROM \"SRL_system\" WHERE (\"name\" = 'xdp_cpm') AND $timeFilter",
     "select": [
      [
       {
        "params": [
         "srl_nokia_system:system/srl_nokia_app_mgmt:app_management/application_state"
        ],
        "type": "field"
       }
      ]
     ],
     "tags": [
      { "key": "name", "operator": "=", "value": "supportd" },
      { "condition": "AND", "key": "source", "operator": "=~", "value": "/^$srl_name$/" }
     ]
    },
    {
     "alias": "xdp_cpm",
     "measurement": "SRL_all",
     "query": "SELECT \"srl_nokia_app_mgmt:app_management/application_state\" FROM \"SRL_system\" WHERE (\"name\" = 'xdp_cpm') AND $timeFilter",
     "select": [
      [
       {
        "params": [
         "srl_nokia_system:system/srl_nokia_app_mgmt:app_management/application_state"
        ],
        "type": "field"
       }
      ]
     ],
     "tags": [
      { "key": "name", "operator": "=", "value": "xdp_cpm" },
      { "condition": "AND", "key": "source", "operator": "=~", "value": "/^$srl_name$/" }
     ]
    },
    {
     "alias": "xdp_lc_1",
     "measurement": "SRL_all",
     "query": "SELECT \"srl_nokia_app_mgmt:app_management/application_state\" FROM \"SRL_system\" WHERE (\"name\" = 'xdp_cpm') AND $timeFilter",
     "select": [
      [
       {
        "params": [
         "srl_nokia_system:system/srl_nokia_app_mgmt:app_management/application_state"
        ],
        "type": "field"
       }
      ]
     ],
     "tags": [
      { "key": "name", "operator": "=", "value": "xdp_lc_1" },
      { "condition": "AND", "key": "source", "operator": "=~", "value": "/^$srl_name$/" }
     ]
    },
    {
     "alias": "xdp_lc_1",
     "measurement": "SRL_all",
     "query": "SELECT \"srl_nokia_app_mgmt:app_management/application_state\" FROM \"SRL_system\" WHERE (\"name\" = 'xdp_cpm') AND $timeFilter",
     "select": [
      [
       {
        "params": [
         "srl_nokia_system:system/srl_nokia_app_mgmt:app_management/application_state"
        ],
        "type": "field"
       }
      ]
     ],
     "tags": [
      { "key": "name", "operator": "=", "value": "xdp_lc_1" },
      { "condition": "AND", "key": "source", "operator": "=~", "value": "/^$srl_name$/" }
     ]
    }
   ]
  },
  {
   "title": "SRL Apps",
   "type": "table",
   "gridPos": { "h": 11, "w": 12, "x": 12, "y": 12 },
   "targets": [
    {
     "groupBy": [
      { "params": [ "name" ], "type": "tag" }
     ],
     "measurement": "SRL_all",
     "select": [
      [
       {
        "params": [
         "srl_nokia_system:system/srl_nokia_app_mgmt:app_management/application_state"
        ],
        "type": "field"
       },
       {
        "params": [],
        "type": "last"
       },
       { "params": [ "status" ], "type": "alias" }
      ],
      [
       {
        "params": [
         "srl_nokia_system:system/srl_nokia_app_mgmt:app_management/application_version"
        ],
        "type": "field"
       },
       {
        "params": [],
        "type": "last"
       },
       { "params": [ "version" ], "type": "alias" }
      ],
      [
       {
        "params": [
         "srl_nokia_system:system/srl_nokia_app_mgmt:app_management/application_pid"
        ],
        "type": "field"
       },
       {
        "params": [],
        "type": "last"
       },
       { "params": [ "pid" ], "type": "alias" }
      ],
      [
       {
        "params": [
         "srl_nokia_system:system/srl_nokia_app_mgmt:app_management/application_last-change"
        ],
        "type": "field"
       },
       {
        "params": [],
        "type": "last"
       },
       { "params": [ "last-change" ], "type": "alias" }
      ]
     ],
     "tags": [
      { "key": "source", "operator": "=~", "value": "/^$srl_name$/" }
     ]
    }
   ]
  },
  {
   "title": "SRL Processes",
   "type": "table",
   "gridPos": { "h": 11, "w": 12, "x": 12, "y": 23 },
   "targets": [
    {
     "groupBy": [
      { "params": [ "pid" ], "type": "tag" }
     ],
     "measurement": "SRL_all",
     "select": [
      [
       {
        "params": [
         "srl_nokia_platform:platform/srl_nokia_platform_control:control/srl_nokia_platform_cpu:process_name"
        ],
        "type": "field"
       },
       {
        "params": [],
        "type": "last"
       },
       { "params": [ "name" ], "type": "alias" }
      ],
      [
       {
        "params": [
         "srl_nokia_platform:platform/srl_nokia_platform_control:control/srl_nokia_platform_cpu:process_start-time"
        ],
        "type": "field"
       },
       {
        "params": [],
        "type": "last"
       },
       { "params": [ "start time" ], "type": "alias" }
      ],
      [
       {
        "params": [
         "srl_nokia_platform:platform/srl_nokia_platform_control:control/srl_nokia_platform_cpu:process_cpu-utilization"
        ],
        "type": "field"
       },
       {
        "params": [],
        "type": "last"
       },
       { "params": [ "cpu utilization" ], "type": "alias" }
      ],
      [
       {
        "params": [
         "srl_nokia_platform:platform/srl_nokia_platform_control:control/srl_nokia_platform_cpu:process_memory-utilization"
        ],
        "type": "field"
       },
       {
        "params": [],
        "type": "last"
       },
       { "params": [ "memory utilization" ], "type": "alias" }
      ],
      [
       {
        "params": [
         "srl_nokia_platform:platform/srl_nokia_platform_control:control/srl_nokia_platform_cpu:process_memory-usage"
        ],
        "type": "field"
       },
       {
        "params": [],
        "type": "last"
       },
       { "params": [ "memory usage" ], "type": "alias" }
      ]
     ],
     "tags": [
      { "key": "source", "operator": "=~", "value": "/^$srl_name$/" }
     ]
    }
   ]
  },
  {
   "title": "Interface Rate",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 26 },
   "yaxes": [
    { "format": "none", "label": "Bps" }
   ],
   "targets": [
    {
     "groupBy": [
      { "params": [ "name" ], "type": "tag" }
     ],
     "measurement": "SRL_all",
     "query": "SELECT \"subinterface/statistics_in-packets\", \"subinterface/statistics_in-octets\", \"subinterface/statistics_out-packets\", \"subinterface/statistics_out-octets\" FROM \"SRL_interface\" WHERE (\"source\" =~ /^$srl_name$/) AND $timeFilter GROUP BY \"name\"",
     "select": [
      [
       {
        "params": [
         "srl_nokia_interfaces:interface/traffic_rate_in-bps"
        ],
        "type": "field"
       }
      ],
      [
       {
        "params": [
         "srl_nokia_interfaces:interface/traffic_rate_out-bps"
        ],
        "type": "field"
       }
      ]
     ],
     "tags": [
      { "key": "source", "operator": "=~", "value": "/^$srl_name$/" }
     ]
    }
   ]
  },
  {
   "title": "Interface Stats",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 34 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "groupBy": [
      { "params": [ "name" ], "type": "tag" }
     ],
     "measurement": "SRL_all",
     "query": "SELECT \"subinterface/statistics_in-packets\", \"subinterface/statistics_in-octets\", \"subinterface/statistics_out-packets\", \"subinterface/statistics_out-octets\" FROM \"SRL_interface\" WHERE (\"source\" =~ /^$srl_name$/) AND $timeFilter GROUP BY \"name\"",
     "select": [
      [
       {
        "params": [
         "srl_nokia_interfaces:interface/subinterface/statistics_in-packets"
        ],
        "type": "field"
       },
       {
        "params": [],
        "type": "non_negative_difference"
       },
       { "params": [ "in-packets" ], "type": "alias" }
      ],
      [
       {
        "params": [
         "srl_nokia_interfaces:interface/subinterface/statistics_out-packets"
        ],
        "type": "field"
       },
       {
        "params": [],
        "type": "non_negative_difference"
       },
       { "params": [ "out-packets" ], "type": "alias" }
      ],
      [
       {
        "params": [
         "srl_nokia_interfaces:interface/subinterface/statistics_in-discarded-packets"
        ],
        "type": "field"
       },
       {
        "params": [],
        "type": "non_negative_difference"
       },
       { "params": [ "in-discarded-packets" ], "type": "alias" }
      ],
      [
       {
        "params": [
         "srl_nokia_interfaces:interface/subinterface/statistics_out-discarded-packets"
        ],
        "type": "field"
       },
       {
        "params": [],
        "type": "non_negative_difference"
       },
       { "params": [ "out-discarded-packets" ], "type": "alias" }
      ]
     ],
     "tags": [
      { "key": "source", "operator": "=~", "value": "/^$srl_name$/" }
     ]
    }
   ]
  },
  {
   "title": "SRL Gnmi",
   "type": "table",
   "gridPos": { "h": 4, "w": 12, "x": 12, "y": 34 },
   "targets": [
    {
     "groupBy": [
      { "params": [ "id" ], "type": "tag" }
     ],
     "measurement": "SRL_all",
     "select": [
      [
       {
        "params": [
         "srl_nokia_system:system/srl_nokia_gnmi_server:gnmi_server/subscription_remote-host"
        ],
        "type": "field"
       },
       {
        "params": [],
        "type": "last"
       },
       { "params": [ "client connected" ], "type": "alias" }
      ],
      [
       {
        "params": [
         "srl_nokia_system:system/srl_nokia_gnmi_server:gnmi_server/subscription_mode"
        ],
        "type": "field"
       },
       {
        "params": [],
        "type": "last"
       },
       { "params": [ "mode" ], "type": "alias" }
      ],
      [
       {
        "params": [
         "srl_nokia_system:system/srl_nokia_gnmi_server:gnmi_server/subscription_sample-interval"
        ],
        "type": "field"
       },
       {
        "params": [],
        "type": "last"
       },
       { "params": [ "interval" ], "type": "alias" }
      ],
      [
       {
        "params": [
         "srl_nokia_system:system/srl_nokia_gnmi_server:gnmi_server/subscription_start-time"
        ],
        "type": "field"
       },
       {
        "params": [],
        "type": "last"
       },
       { "params": [ "start time" ], "type": "alias" }
      ],
      [
       {
        "params": [
         "srl_nokia_system:system/srl_nokia_gnmi_server:gnmi_server/subscription_paths_0"
        ],
        "type": "field"
       },
       {
        "params": [],
        "type": "last"
       },
       { "params": [ "path" ], "type": "alias" }
      ]
     ],
     "tags": [
      { "key": "source", "operator": "=~", "value": "/^$srl_name$/" }
     ]
    }
   ]
  },
  {
   "title": "SRL Interfaces",
   "type": "table",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 38 },
   "targets": [
    {
     "groupBy": [
      { "params": [ "name" ], "type": "tag" }
     ],
     "measurement": "SRL_all",
     "query": "SELECT \"subinterface_name\", last(\"subinterface_oper-state\") AS \"status\", \"subinterface/statistics_in-packets\" AS \"in-packets\", \"subinterface/statistics_out-packets\" AS \"out-packets\", \"subinterface/statistics_in-discarded-packets\" AS \"in-discarded\", \"subinterface/statistics_out-discarded-packets\" AS \"out-discarded\" FROM \"SRL_interface\" WHERE (\"source\" =~ /^$srl_name$/) AND $timeFilter GROUP BY \"name\"",
     "select": [
      [
       {
        "params": [
         "srl_nokia_interfaces:interface/subinterface_name"
        ],
        "type": "field"
       }
      ],
      [
       {
        "params": [
         "srl_nokia_interfaces:interface/subinterface_oper-state"
        ],
        "type": "field"
       },
       {
        "params": [],
        "type": "last"
       },
       { "params": [ "status" ], "type": "alias" }
      ],
      [
       {
        "params": [
         "srl_nokia_interfaces:interface/subinterface/statistics_in-packets"
        ],
        "type": "field"
       },
       { "params": [ "in-packets" ], "type": "alias" }
      ],
      [
       {
        "params": [
         "srl_nokia_interfaces:interface/subinterface/statistics_out-packets"
        ],
        "type": "field"
       },
       { "params": [ "out-packets" ], "type": "alias" }
      ],
      [
       {
        "params": [
         "srl_nokia_interfaces:interface/subinterface/statistics_in-discarded-packets"
        ],
        "type": "field"
       },
       { "params": [ "in-discarded" ], "type": "alias" }
      ],
      [
       {
        "params": [
         "srl_nokia_interfaces:interface/subinterface/statistics_out-discarded-packets"
        ],
        "type": "field"
       },
       { "params": [ "out-discarded" ], "type": "alias" }
      ]
     ],
     "tags": [
      { "key": "source", "operator": "=~", "value": "/^$srl_name$/" }
     ]
    }
   ]
  },
  {
   "title": "Queue Stats",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 42 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "groupBy": [
      { "params": [ "name" ], "type": "tag" },
      { "params": [ "queue_id" ], "type": "tag" }
     ],
     "measurement": "SRL_all",
     "query": "SELECT \"srl_nokia_qos:queue_statistics/queue_transmitted-packets\" AS \"queue_transmitted-packets\", \"srl_nokia_qos:queue_statistics/queue_transmitted-octets\" AS \"queue_transmitted-octets\", \"srl_nokia_qos:queue_statistics/queue_final-dropped-packets\" AS \"queue_final-dropped-packets\", \"srl_nokia_qos:queue_statistics/queue_final-dropped-octets\" AS \"queue_final-dropped-octets\" FROM \"SRL_interface\" WHERE (\"source\" =~ /^$srl_name$/) AND $timeFilter GROUP BY \"queue_id\", \"name\"",
     "select": [
      [
       {
        "params": [
         "srl_nokia_interfaces:interface/srl_nokia_qos:queue_statistics/unicast_queue_transmitted-packets"
        ],
        "type": "field"
       },
       {
        "params": [],
        "type": "non_negative_difference"
       },
       { "params": [ "queue_transmitted-packets" ], "type": "alias" }
      ],
      [
       {
        "params": [
         "srl_nokia_interfaces:interface/srl_nokia_qos:queue_statistics/unicast_queue_final-dropped-packets"
        ],
        "type": "field"
       },
       {
        "params": [],
        "type": "non_negative_difference"
       },
       { "params": [ "queue_final-dropped-packets" ], "type": "alias" }
      ]
     ],
     "tags": [
      { "key": "source", "operator": "=~", "value": "/^$srl_name$/" }
     ]
    }
   ]
  },
  {
   "title": "SRL Queues",
   "type": "table",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 44 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "groupBy": [
      { "params": [ "name" ], "type": "tag" },
      { "params": [ "queue_id" ], "type": "tag" }
     ],
     "measurement": "SRL_all",
     "query": "SELECT \"srl_nokia_qos:queue_statistics/queue_transmitted-packets\" AS \"queue_transmitted-packets\", \"srl_nokia_qos:queue_statistics/queue_transmitted-octets\" AS \"queue_transmitted-octets\", \"srl_nokia_qos:queue_statistics/queue_final-dropped-packets\" AS \"queue_final-dropped-packets\", \"srl_nokia_qos:queue_statistics/queue_final-dropped-octets\" AS \"queue_final-dropped-octets\" FROM \"SRL_interface\" WHERE (\"source\" =~ /^$srl_name$/) AND $timeFilter GROUP BY \"queue_id\", \"name\"",
     "select": [
      [
       {
        "params": [
         "srl_nokia_interfaces:interface/srl_nokia_qos:queue_statistics/unicast_queue_transmitted-packets"
        ],
        "type": "field"
       },
       {
        "params": [],
        "type": "last"
       },
       { "params": [ "transmitted-packets" ], "type": "alias" }
      ],
      [
       {
        "params": [
         "srl_nokia_interfaces:interface/srl_nokia_qos:queue_statistics/unicast_queue_transmitted-octets"
        ],
        "type": "field"
       },
       {
        "params": [],
        "type": "last"
       },
       { "params": [ "transmitted-octets" ], "type": "alias" }
      ],
      [
       {
        "params": [
         "srl_nokia_interfaces:interface/srl_nokia_qos:queue_statistics/unicast_queue_final-dropped-packets"
        ],
        "type": "field"
       },
       {
        "params": [],
        "type": "last"
       },
       { "params": [ "dropped-packets" ], "type": "alias" }
      ],
      [
       {
        "params": [
         "srl_nokia_interfaces:interface/srl_nokia_qos:queue_statistics/unicast_queue_final-dropped-octets"
        ],
        "type": "field"
       },
       {
        "params": [],
        "type": "last"
       },
       { "params": [ "dropped-octets" ], "type": "alias" }
      ]
     ],
     "tags": [
      { "key": "source", "operator": "=~", "value": "/^$srl_name$/" }
     ]
    }
   ]
  }
 ]
}